CREATE TABLE dish_types
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dish_type VARCHAR(255),
    CONSTRAINT pk_dish_types PRIMARY KEY (id)
);

CREATE TABLE dishes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dish_name  VARCHAR(255),
    dish_price DECIMAL,
    type_id    BIGINT,
    CONSTRAINT pk_dishes PRIMARY KEY (id)
);

CREATE TABLE menu_dishes
(
    dish_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    CONSTRAINT pk_menu_dishes PRIMARY KEY (dish_id, menu_id)
);

CREATE TABLE menu_list
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    menu_title      VARCHAR(255),
    menu_start_time time WITHOUT TIME ZONE,
    menu_end_time   time WITHOUT TIME ZONE,
    CONSTRAINT pk_menu_list PRIMARY KEY (id)
);

ALTER TABLE dishes
    ADD CONSTRAINT FK_DISHES_ON_TYPE FOREIGN KEY (type_id) REFERENCES dish_types (id);

ALTER TABLE menu_dishes
    ADD CONSTRAINT fk_mendis_on_dish_entity FOREIGN KEY (dish_id) REFERENCES dishes (id);

ALTER TABLE menu_dishes
    ADD CONSTRAINT fk_mendis_on_menu_entity FOREIGN KEY (menu_id) REFERENCES menu_list (id);