# my laptop feeling dead inside after this
version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'restaurant_db'
    volumes:
      - '.:/docker-entrypoint-initdb.d'
    ports:
      - "5434:5432"
  web-app-backend:
    build: ../
    restart: always
    environment:
      DB_URL: postgres
      DB_USERNAME: "postgres"
      DB_PASSWORD: 'admin'
      DB_NAME: 'restaurant_db'
    ports:
      - "8080:8080"
  web-app-frontend:
    image: web-app-frontend
    depends_on:
      - web-app-backend
    ports:
      - "8081:5173"