CREATE TABLE dish_types
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dish_type VARCHAR(255),
    CONSTRAINT pk_dish_types PRIMARY KEY (id)
);

INSERT INTO dish_types
VALUES (nextval('dish_types_id_seq'), 'Французская');
INSERT INTO dish_types
VALUES (nextval('dish_types_id_seq'), 'Итальянская');
INSERT INTO dish_types
VALUES (nextval('dish_types_id_seq'), 'Русская');
INSERT INTO dish_types
VALUES (nextval('dish_types_id_seq'), 'Грузинская');

CREATE TABLE dishes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dish_name  VARCHAR(255),
    dish_price DECIMAL,
    type_id    BIGINT,
    CONSTRAINT pk_dishes PRIMARY KEY (id)
);

INSERT INTO dishes
VALUES (nextval('dishes_id_seq'), 'Круассан', 250, 1);
INSERT INTO dishes
VALUES (nextval('dishes_id_seq'), 'Луковый суп', 500, 1);
INSERT INTO dishes
VALUES (nextval('dishes_id_seq'), 'Багет с чесноком и сыром', 150, 1);

INSERT INTO dishes
VALUES (nextval('dishes_id_seq'), 'Паста карбонара', 450, 2);
INSERT INTO dishes
VALUES (nextval('dishes_id_seq'), 'Паста болоньезе', 300, 2);
INSERT INTO dishes
VALUES (nextval('dishes_id_seq'), 'Пицца с ананасами', 600, 2);

INSERT INTO dishes
VALUES (nextval('dishes_id_seq'), 'Щи', 350, 3);
INSERT INTO dishes
VALUES (nextval('dishes_id_seq'), 'Пельмени', 240, 3);
INSERT INTO dishes
VALUES (nextval('dishes_id_seq'), 'Окрошка', 270, 3);

INSERT INTO dishes
VALUES (nextval('dishes_id_seq'), 'Хачапури', 450, 4);
INSERT INTO dishes
VALUES (nextval('dishes_id_seq'), 'Джонджоли', 500, 4);
INSERT INTO dishes
VALUES (nextval('dishes_id_seq'), 'Бадриджани', 150, 1);

CREATE TABLE menu_dishes
(
    dish_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    CONSTRAINT pk_menu_dishes PRIMARY KEY (dish_id, menu_id)
);

CREATE TABLE menu_list
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    menu_title      VARCHAR(255),
    menu_start_time time WITHOUT TIME ZONE,
    menu_end_time   time WITHOUT TIME ZONE,
    CONSTRAINT pk_menu_list PRIMARY KEY (id)
);

INSERT INTO menu_list
VALUES (nextval('menu_list_id_seq'), 'Утреннее меню по Русски', '07:00:00', '09:00:00');
INSERT INTO menu_list
VALUES (nextval('menu_list_id_seq'), 'Обеденное меню по Итальянски', '11:00:00', '13:00:00');
INSERT INTO menu_list
VALUES (nextval('menu_list_id_seq'), 'Вечернее меню по Грузински', '18:00:00', '23:00:00');
INSERT INTO menu_list
VALUES (nextval('menu_list_id_seq'), 'Ночное меню по Французски', '00:00:00', '05:00:00');

-- RUSSIAN
INSERT INTO menu_dishes
VALUES (7, 1);
INSERT INTO menu_dishes
VALUES (8, 1);
INSERT INTO menu_dishes
VALUES (9, 1);
-- ITALIAN
INSERT INTO menu_dishes
VALUES (4, 2);
INSERT INTO menu_dishes
VALUES (5, 2);
INSERT INTO menu_dishes
VALUES (6, 2);
-- GEORGIAN
INSERT INTO menu_dishes
VALUES (10, 3);
INSERT INTO menu_dishes
VALUES (11, 3);
INSERT INTO menu_dishes
VALUES (12, 3);
-- FRENCH
INSERT INTO menu_dishes
VALUES (1, 4);
INSERT INTO menu_dishes
VALUES (2, 4);
INSERT INTO menu_dishes
VALUES (3, 4);

ALTER TABLE dishes
    ADD CONSTRAINT FK_DISHES_ON_TYPE FOREIGN KEY (type_id) REFERENCES dish_types (id);

ALTER TABLE menu_dishes
    ADD CONSTRAINT fk_mendis_on_dish_entity FOREIGN KEY (dish_id) REFERENCES dishes (id);

ALTER TABLE menu_dishes
    ADD CONSTRAINT fk_mendis_on_menu_entity FOREIGN KEY (menu_id) REFERENCES menu_list (id);